import {
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
} from '@angular/material';

import { FlexLayoutModule } from '@angular/flex-layout';
import { NgModule } from '@angular/core';
import { ScrollingModule } from '@angular/cdk/scrolling';

@NgModule({
    imports: [
        MatFormFieldModule,
        MatInputModule,
        MatButtonModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatSidenavModule,
        MatTableModule,
        MatSortModule,
        MatCheckboxModule,
        MatInputModule,
        MatFormFieldModule,
        MatSnackBarModule,
        MatSelectModule,
        MatExpansionModule,
        MatTabsModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatButtonToggleModule,
        MatPaginatorModule,
        MatSlideToggleModule,
        MatTooltipModule,
        MatStepperModule,
        MatListModule,
        MatAutocompleteModule,
        MatRadioModule,
        MatDividerModule,
        MatChipsModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatProgressBarModule,
        MatSortModule,
        FlexLayoutModule,
        ScrollingModule
    ],
    exports: [
        FlexLayoutModule,
        MatFormFieldModule,
        MatInputModule,
        MatButtonModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatSidenavModule,
        MatTableModule,
        MatSortModule,
        MatCheckboxModule,
        MatInputModule,
        MatFormFieldModule,
        MatSnackBarModule,
        MatSelectModule,
        MatExpansionModule,
        MatTabsModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatButtonToggleModule,
        MatPaginatorModule,
        MatSlideToggleModule,
        MatTooltipModule,
        MatStepperModule,
        MatListModule,
        MatAutocompleteModule,
        MatRadioModule,
        MatDividerModule,
        MatChipsModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatProgressBarModule,
        ScrollingModule
    ]
})
export class MaterialModule { }

